export default {
  id: "tencentcloud-intl",
  priority: 81,
  hasFree: true,
  alias: "tci",
  display: {
    name: "TencentCloud Intl",
    icon: "cloud",
    color: "#0052D9",
    textIcon: "TI",
    website: "https://intl.cloud.tencent.com",
    notice: {
      apiKeyUrl: "https://console.tencentcloud.com/tokenhub/apikey",
    },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://tokenhub-intl.tencentcloudmaas.com/v1/chat/completions",
    validateUrl: "https://tokenhub-intl.tencentcloudmaas.com/v1/models",
  },
  models: [
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-5-turbo", name: "GLM 5 Turbo" },
    { id: "glm-5v-turbo", name: "GLM 5V Turbo" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-pro-202606", name: "DeepSeek V4 Pro (Vendor Direct)" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-flash-202605", name: "DeepSeek V4 Flash (Vendor Direct)" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
  ],
  serviceKinds: ["llm"],
};
